### ISSUE TITLE
how to enable rofi 

### ISSUE THREAD

**Issue by drmarwat** [ssleert/qpwm#9]
I edited config.h file as below

// app launcher
// rofi or dmenu
#const char *menu[] = {"dmenu_run", 0};
const char *menu[] = {"rofi -show run", 0};

then 

sudo make clean install
rm -f qpwm *.o
cc -std=c99 -Ofast -flto -march=native -funroll-loops -Wall -Wextra -pedantic -Wold-style-declaration -Wmissing-prototypes -Wno-unused-parameter -o qpwm qpwm.c -lX11 
In file included from qpwm.c:89:
config.h:19:2: error: invalid preprocessing directive #const
   19 | #const char *menu[] = {"dmenu_run", 0};
      |  ^~~~~
make: *** [Makefile:13: qpwm] Error 1

so whats the correct way of enabling rofi?

**Comment by 4k1v** [comment]
**i think you need write** "//const char *menu[] = {"dmenu_run", 0};" **instead** "#const char *menu[] = {"dmenu_run", 0};"
